githubConfigUrl: "https://github.com/llvm"
githubConfigSecret: "github-token"

minRunners: 1
maxRunners: 2

template:
  metadata:
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
  spec:
    tolerations:
    - key: "node.kubernetes.io/os"
      operator: "Equal"
      value: "windows"
      effect: "NoSchedule"
    - key: "premerge-platform"
      operator: "Equal"
      value: "windows"
      effect: "NoSchedule"
    nodeSelector:
      premerge-platform: windows
    containers:
      - name: runner
        resources:
          requests:
            cpu: 55
        image: ghcr.io/llvm/ci-windows-2019:latest
        command: ["run.cmd"]
        args: ["--jitconfig", "$(ACTIONS_RUNNER_INPUT_JITCONFIG)"]
        env:
          - name: DISABLE_RUNNER_UPDATE
            value: "true"
